### ISSUE TITLE
Goのフレームワークの選定

### ISSUE THREAD

**Issue by taiga39** [taiga39/go-mission#1]
# Goのフレームワークの選定
Goのフレームワークについて、メリットとデメリットを調べミッションで使用するフレームワークを決める。

## 選んだフレームワーク
「echo」を選択。
まず「Revel」と「Beego」に関してはMVCモデルであるために除外。
理由はMVCモデルのRuby on Railsの利用経験があり、M = DBという考えが抜けず、
クリーンアーキテクチャを理解し実装するという目標とズレてしまう気がしたため。

「Gin」と「echo」については機能面で差を感じることができなかったため、ドキュメントのみやすさで選択。
[Ginのドキュメント](https://gin-gonic.com/ja/docs/)は日本語に対応しているメリットがあるものの、
使いたい機能をうまく見つけることができなかった。
「routing」、「ルーティング」というワードで検索しても検索結果はno resultとなる。

一方で[echoのドキュメント](https://echo.labstack.com/guide)は日本語に対応していないが、
サイドバーに機能ごとのリンクが表示されている点や「routing」と検索した検索結果が表示されていることもあり、
実装する際の調べやすさが優秀だと感じた。

上記の理由により「echo」を選択した。

#### メリット
フルスタックフレームワークであること。
MVCモデルで作られている。
#### メリット
フルスタックフレームワークであること。
MVCモデルで作られている。
#### メリット
日本語のドキュメントが用意されている点。
#### メリット
ドキュメントが見やすい点。
#### デメリット

**Comment by GuiltyMorishita** [comment]
クリーンアーキテクチャとは？
M = DBなのか？

**Comment by GuiltyMorishita** [comment]
LGTM
