### ISSUE TITLE
コードが正しく動作している根拠（リクエストが正しく動作しているか）

### ISSUE THREAD

**Issue by taiga39** [taiga39/go-mission#4]
## 問題背景
`localhost:5555/users/get`にアクセスした際に、
サーバー側のログでステータスコードが「200」と表示されていても、
クライアント側は「201」と表示されているかもしれない。
そのリクエストが正しく動作している根拠はどこにあるか。

### 解答
リクエストを送ったクライアント側でサーバーから受け取ったレスポンスを見る。

### 理由
HTTPではクライアントが出したリクエストをサーバーで処理してレスポンスを返す。
そしてリクエストを出したクライアントはレスポンスが返るまで待機する。

つまりリクエストを出してレスポンスを受け取り処理をするまでが一連の流れであるため、
問題背景のようにサーバー側で行った処理のログを見ても、途中経過を見ているだけである。
なのでクライアント側でレスポンスを確認することが正しく動作している根拠となる。

## 参考資料
山本陽平、『Webを支える技術』、 技術評論社、2017年、P73~P76を要約

**Comment by GuiltyMorishita** [comment]
https://paw.cloud/

**Comment by GuiltyMorishita** [comment]
LGTM
